### ISSUE TITLE
Mobile Detection is broken for touch sensitive laptops

### ISSUE THREAD

**Issue by Logiraptor** [olahol/greasyphone#1]
When I launch the server and point my browser at it on my laptop, I am presented with a controller. This is because my laptop has a touchscreen and that's how the code currently detects whether it's on a mobile device. It seems the recommended way to do that check is by looking at the user agent.

**Comment by olahol** [comment]
You right, that was oversight by me. I fixed it in c7510a63b06a1940b01ca3a9d14ddc657b36d319, check if it works for you.
