### ISSUE TITLE
Controller Text is selected when holding buttons.

### ISSUE THREAD

**Issue by Logiraptor** [olahol/greasyphone#2]
See the screenshot below:

![Screenshot](http://i.imgur.com/U3Je7aT.png)

After holding down the A button, Chrome for Android thinks I'm trying to select text on the page, so this ui pops up and blocks other touch events. This makes it difficult to play many games which require holding down buttons.

**Comment by olahol** [comment]
So that's why the input was so choppy, nice catch. I have pushed a fix so that it disallows all text selecting on the controller. Thanks mate :+1:
